package com.relylabs.around.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id(autoincrement = true)
    private Long id;
    private int UserId;
    private String FirstName;
    private String LastName;
    private String Email;
    private String PhoneNo;
    private String Location;
    private String ProfilePicURL;
    private Boolean IsOTPVerified;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, int UserId, String FirstName, String LastName, String Email, String PhoneNo, String Location, String ProfilePicURL, Boolean IsOTPVerified) {
        this.id = id;
        this.UserId = UserId;
        this.FirstName = FirstName;
        this.LastName = LastName;
        this.Email = Email;
        this.PhoneNo = PhoneNo;
        this.Location = Location;
        this.ProfilePicURL = ProfilePicURL;
        this.IsOTPVerified = IsOTPVerified;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUserId() {
        return UserId;
    }

    public void setUserId(int UserId) {
        this.UserId = UserId;
    }

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getPhoneNo() {
        return PhoneNo;
    }

    public void setPhoneNo(String PhoneNo) {
        this.PhoneNo = PhoneNo;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String Location) {
        this.Location = Location;
    }

    public String getProfilePicURL() {
        return ProfilePicURL;
    }

    public void setProfilePicURL(String ProfilePicURL) {
        this.ProfilePicURL = ProfilePicURL;
    }

    public Boolean getIsOTPVerified() {
        return IsOTPVerified;
    }

    public void setIsOTPVerified(Boolean IsOTPVerified) {
        this.IsOTPVerified = IsOTPVerified;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
